GET http://localhost:5500/cars

###
GET http://localhost:5500/api/admin/dealers

###
POST http://localhost:5500/api/admin/dealers
Content-Type: application/json

{
  "name": "Fabien Karmel",
  "username": "MrSociety404",
  "password": "root",
  "image": "https://i.imgur.com/zYujvDw.jpg"
}